spring:
  profiles:
    active: database

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
         show_sql: true
         format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
