spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OneQJob?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          show_sql: true
          format_sql: true

  security:
    csrf:
      enabled: false

coolsms:
  api:
    key: NCSR7TXKSHJFOBR8
    secret: WG5XTM5JHINUVFRXKZXI70HSPUYPDGUX
    url: https://api.coolsms.co.kr

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        security: DEBUG
        web: DEBUG
