spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true

  security:
    csrf:
      enabled: false


coolsms:
  api:
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_API_SECRET}
    url: ${COOLSMS_API_URL}

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        security: DEBUG
        web: DEBUG

